# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-19 09:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='album_track',
        ),
        migrations.RemoveField(
            model_name='album',
            name='album_genre',
        ),
        migrations.AddField(
            model_name='album',
            name='album_genre',
            field=models.ManyToManyField(to='ms.Genre'),
        ),
        migrations.AlterField(
            model_name='album',
            name='album_singer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ms.Singer'),
        ),
    ]
