# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-19 09:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ms', '0004_auto_20170819_1241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='album_genre',
        ),
        migrations.AddField(
            model_name='album',
            name='album_genre',
            field=models.ForeignKey(default=123131, on_delete=django.db.models.deletion.CASCADE, to='ms.Genre'),
            preserve_default=False,
        ),
    ]
